# Generated by Django 4.2.6 on 2023-10-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description_visibility',
            field=models.CharField(default='public friends', max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_visibility',
            field=models.CharField(default='public friends', max_length=20),
        ),
    ]
