# Generated by Django 4.2.6 on 2023-10-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_achievement_ach_title_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='edu_title_visibility',
            field=models.CharField(blank=True, default='public friends', max_length=20, null=True),
        ),
    ]
