# Generated by Django 4.2.6 on 2023-10-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_education_edu_title_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ex_jobtitle_visibility',
            field=models.CharField(blank=True, default='public friends', max_length=20, null=True),
        ),
    ]
