# Generated by Django 4.2.6 on 2023-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_workportfolio_work_des_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='workportfolio',
            name='work_link_visibility',
            field=models.CharField(blank=True, default='public friends', max_length=20, null=True),
        ),
    ]
