# Generated by Django 4.2.6 on 2023-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_workportfolio_work_link_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='ach_title_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='overview_contact_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_title_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ex_jobtitle_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='placelived',
            name='place_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_name_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skills_name_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skills_rating_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workportfolio',
            name='work_des_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workportfolio',
            name='work_link_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workportfolio',
            name='work_title_visibility',
            field=models.CharField(blank=True, default='Public Friends', max_length=20, null=True),
        ),
    ]
